import glob
import os


configfile: "config/config.yml"


# Access the data folder from the config
data_folder = config["data"]["folder"]
reference_folder = config["reference"]["folder"]
genome_name = config["reference"]["genome"]
reference = os.path.join(reference_folder, genome_name)
reference_idx = f"{reference}.fai"
reference_dict = f"{reference}.dict"
known_sites_folder = config["known_sites"]["folder"]
known_filename = config["known_sites"]["filename"]
known_sites = os.path.join(known_sites_folder, known_filename)
known_sites_idx = f"{known_sites}.idx"

sample_files = glob.glob(os.path.join(data_folder, "*.bam"))
samples = [os.path.basename(f).replace(".bam", "") for f in sample_files]

recalibrated_files = [f"results/recal/{sample}.bam" for sample in samples]

first_summaries = [f"results/stats/{sample}_before_recal.summary.txt" for sample in samples]
second_summaries = [f"results/stats/{sample}_after_recal.summary.txt" for sample in samples]
rule all:
    input:
        recalibrated_files,
        first_summaries,
        second_summaries


include: "rules/add_or_replace_rg.smk"
include: "rules/mark_duplicates.smk"
include: "rules/index_genome.smk"
include: "rules/split_n_cigar_reads.smk"
include: "rules/recalibration.smk"
include: "rules/alignment_summary.smk"
