import glob
import os


configfile: "config/config.yml"


# Access the data folder from the config
data_folder = config["data"]["folder"]


sample_files = glob.glob(os.path.join(data_folder, "*.bam"))
samples = [os.path.basename(f).replace(".bam", "") for f in sample_files]
read_groups = [f"results/grouped/{sample}.bam" for sample in samples]
deduped_files = [f"results/dedup/{sample}.bam" for sample in samples]


rule all:
    input:
        deduped_files,


include: "rules/add_or_replace_rg.smk"
include: "rules/mark_duplicates.smk"
