name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  Formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Formatting
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          VALIDATE_SNAKEMAKE_SNAKEFMT: true

  Linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Lint workflow
      uses: snakemake/snakemake-github-action@v1.24.0
      with:
        directory: .
        snakefile: workflow/Snakefile
        args: "--lint"

  

  Testing:
    runs-on: ubuntu-latest
    needs: 
      - Linting
      - Formatting
    steps:
    - uses: actions/checkout@v4


    - name: Test workflow
      uses: snakemake/snakemake-github-action@v1.24.0
      with:
        directory: '.test'
        snakefile: 'workflow/Snakefile'
        args: "--dry-run --use-conda --show-failed-logs --cores 3 --conda-cleanup-pkgs cache --all-temp"
        stagein: |
          echo "Current working directory: $(pwd)"
          echo "Listing contents of current directory:"
          ls -R
          echo "Listing contents of .test directory:"
          ls -R .test
          echo "Listing contents of .test/config directory:"
          ls -R .test/config
          echo "Listing contents of .test/data directory:"
          ls -R .test/data
    - name: Test report
      uses: snakemake/snakemake-github-action@v1.24.0
      with:
        directory: '.test'
        snakefile: 'workflow/Snakefile'
        args: "--report report.zip"